# Generated by Django 3.0.2 on 2020-01-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('sponsor', models.CharField(max_length=200)),
                ('manager_name', models.CharField(max_length=200)),
                ('manager_approve', models.BooleanField(default=False)),
                ('ceo_approve', models.BooleanField(default=False)),
            ],
        ),
    ]
