# Generated by Django 3.0.2 on 2020-01-16 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='ceo_approve',
            new_name='CEO_approve',
        ),
    ]
