# Generated by Django 3.0.2 on 2020-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20200116_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
