# Generated by Django 3.0.2 on 2020-01-28 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_partners_date_add'),
        ('partners', '0003_auto_20200125_1007'),
    ]

    operations = [
    ]
