# Generated by Django 3.0.2 on 2020-01-28 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_merge_20200128_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partners',
            name='CEO_approve',
        ),
        migrations.RemoveField(
            model_name='partners',
            name='manager_approve',
        ),
    ]
