# Generated by Django 3.0.2 on 2020-01-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200125_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyregpartners',
            name='CEO_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partyregpartners',
            name='manager_approve',
            field=models.BooleanField(default=False),
        ),
    ]
